sudo: false
language: node_js
node_js:
  - 4
  - 6
  - "stable"

cache: yarn

env:
  global:
    COVERALLS_PARALLEL: true

script: "yarn cover"
after_success: "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
